services:
  postgres:
    image: postgres:17
    container_name: codebase-visualizer-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: codebase_visualizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FerariF12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
