CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  source_filename TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready',
  total_files INTEGER NOT NULL DEFAULT 0,
  total_functions INTEGER NOT NULL DEFAULT 0,
  total_loc INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS code_files (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  name TEXT NOT NULL,
  extension TEXT NOT NULL,
  language TEXT NOT NULL,
  loc INTEGER NOT NULL DEFAULT 0,
  building_height DOUBLE PRECISION NOT NULL DEFAULT 4,
  building_width DOUBLE PRECISION NOT NULL DEFAULT 4,
  building_depth DOUBLE PRECISION NOT NULL DEFAULT 4,
  position_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  position_z DOUBLE PRECISION NOT NULL DEFAULT 0,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS code_functions (
  id SERIAL PRIMARY KEY,
  file_id INTEGER NOT NULL REFERENCES code_files(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  start_line INTEGER NOT NULL DEFAULT 1,
  end_line INTEGER NOT NULL DEFAULT 1,
  complexity INTEGER NOT NULL DEFAULT 1,
  room_width DOUBLE PRECISION NOT NULL DEFAULT 1,
  room_depth DOUBLE PRECISION NOT NULL DEFAULT 1,
  room_height DOUBLE PRECISION NOT NULL DEFAULT 1,
  offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  offset_y DOUBLE PRECISION NOT NULL DEFAULT 0,
  offset_z DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_code_files_project_id ON code_files(project_id);
CREATE INDEX IF NOT EXISTS idx_code_functions_file_id ON code_functions(file_id);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);
